[".config/vim/autoload/plug.vim"]
    type = "file"
    url = "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    refreshPeriod = "168h"

# [".local/share/themes/WhiteSur-gtk-theme"]
#     type = "archive"
#     source = "https://github.com/vinceliuice/WhiteSur-gtk-theme/archive/refs/heads/master.zip"
#     exact = true
#     stripComponents = 1
#     refreshPeriod = "168h"

# [".local/share/icons/WhiteSur-icon-theme"]
#     type = "archive"
#     source = "https://github.com/vinceliuice/WhiteSur-icon-theme/archive/refs/heads/master.zip"
#     exact = true
#     stripComponents = 1
#     refreshPeriod = "168h"

# [".local/share/backgrounds/WhiteSur-wallpapers"]
#     type = "archive"
#     source = "https://github.com/vinceliuice/WhiteSur-wallpapers/archive/refs/heads/master.zip"
#     exact = true
#     stripComponents = 1
#     refreshPeriod = "168h"

# [".local/share/fonts/HackGenNerd"]
#     type = "archive"
#     source = "https://github.com/yuru7/HackGen/releases/download/v2.9.0/HackGenNerd_v2.9.0.zip"
#     exact = true
#     stripComponents = 1
#     refreshPeriod = "168h"

# [".local/share/fonts/RobotoMono"]
#     type = "archive"
#     source = "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.0/RobotoMono.zip"
#     exact = true
#     stripComponents = 1
#     refreshPeriod = "168h"
