services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-ubuntu-xfce-xrdp
    ports:
      - "8787:80"
      - "3389:3389"
    environment:
      - ENV=production
    networks:
      - app-network

  ipfs:
    image: ipfs/kubo
    container_name: ipfs
    networks:
      - app-network
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001
    volumes:
      - ./private_dot_config/ipfs/config:/home/ubuntu/.config/ipfs/config
      - ./private_data:/export
      - ./private_dot_config/ipfs/executable_entrypoint.sh:/container-init.d/entrypoint.sh #init直後のdaemon起動前に実行されるshをマウント
    environment:
      IPFS_PROFILE: server # server modeで起動
      IPFS_PATH: /home/ubuntu/.config/ipfs
    # command: ipfs daemon
    restart: always

networks:
  app-network:
    driver: bridge
