services:
  app:
    image: my-image-name:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app-container
    ports:
      - "8787:80"
      - "3389:3389"
    environment:
      - ENV=production
