#!/bin/sh

# chsh -s /bin/zsh

HOSTNAME="$(uname -n)"
export HOSTNAME

## '${VAR} "${VAR}" "${VAR:=var}"' は環境変数 ' : ' で区切り
export DOTFILES="${HOME}/dotfiles"

# XDG DIRECTORY を作成して権限を700に設定
mkdir -p \
    "${XDG_DATA_HOME:-$HOME/.local/share}" \
    "${XDG_CONFIG_HOME:-$HOME/.config}" \
    "${XDG_STATE_HOME:-$HOME/.local/state}" \
    "${XDG_CACHE_HOME:-$HOME/.cache}" \
    "${HOME}/data"
chmod 700 \
    "${XDG_CONFIG_HOME:-$HOME/.config}" \
    "${XDG_DATA_HOME:-$HOME/.local/share}" \
    "${XDG_STATE_HOME:-$HOME/.local/state}" \
    "${XDG_CACHE_HOME:-$HOME/.cache}" \
    "${HOME}/data"

# XDG DIRECTORY
export XDG_CONFIG_HOME=${HOME}/.config
export XDG_STATE_HOME=${HOME}/.local/state
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_DATA_DIRS="/usr/local/share:/usr/share:${HOME}/data"

export XDG_CACHE_HOME=${HOME}/.cache
export XDG_CONFIG_DIRS="/etc/xdg/xdg-ubuntu:/etc/xdg"

XDG_RUNTIME_DIR=/run/user/$(id -u)
export XDG_RUNTIME_DIR

export XDG_DESKTOP_DIR=${HOME}/Desktop
export XDG_DOWNLOAD_DIR=${HOME}/Downloads
export XDG_DOCUMENTS_DIR=${HOME}/Documents
export XDG_PUBLICSHARE_DIR=${HOME}/Public
export XDG_MUSIC_DIR=${HOME}/Music
export XDG_PICTURES_DIR=${HOME}/Pictures
export XDG_VIDEOS_DIR=${HOME}/Movies
export XDG_TEMPLATES_DIR=${HOME}/Templates
#export XDG_SESSION_TYPE=X11
#export XDG_SESSION_ID=1

export TZ="Asia/Tokyo"
export LANG="ja_JP.UTF-8"
export LC_ALL="ja_JP.UTF-8"
# TUIの表示乱れ防止
export LC_CTYPE="en_US.UTF-8"

export TMPDIR="/tmp"
export TERM="xterm-256color"

if command -v code >/dev/null 2>&1; then
    export EDITOR="code"
elif command -v codium >/dev/null 2>&1; then
    export EDITOR="codium"
else
    export EDITOR="vim"
fi

# if [ -z "$DISPLAY" ]; then
#     export DISPLAY=":0"
# fi

export PS1="\[\e[32m\]\u@\h\[\e[m\]:\[\e[34m\]\w\[\e[m\] \$ "

export PROMPT='%F{green}%n@%m%f:%F{blue}% ~ %f%F{yellow}$%f '

# export ZDOTDIR="${HOME}"

# パスを再設定
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

export HOMEBREW_PREFIX="/opt/homebrew"

mkdir -p ${XDG_CONFIG_HOME}/mise
export MISE_CONFIG_DIR=${XDG_CONFIG_HOME}/mise
touch ${MISE_CONFIG_DIR}/shorthands.toml
export MISE_SHORTHANDS_FILE=${MISE_CONFIG_DIR}/shorthands.toml

mkdir -p ${XDG_CONFIG_HOME}/aquaproj-aqua ${XDG_DATA_HOME}/aquaproj-aqua
# cp -R "${AQUA_ROOT_DIR:-$HOME/.aqua}" "${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua"
# mv "${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua/global" "${XDG_CONFIG_HOME:-$HOME/.config}/aquaproj-aqua"
export PATH="${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua/bin:${PATH}"
export AQUA_GLOBAL_CONFIG="${AQUA_GLOBAL_CONFIG:-}:${XDG_CONFIG_HOME:-$HOME/.config}/aquaproj-aqua/aqua.yaml"

mkdir -p "${XDG_CONFIG_HOME}/vim"
export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
#export VIMINIT='let $MYVIMRC = !has("nvim") ? "${XDG_CONFIG_HOME}/vim/vimrc" : "${XDG_CONFIG_HOME}/nvim/init.vim" | so $MYVIMRC'

# mkdir -p "${XDG_CONFIG_HOME}/spacemacs"
# export SPACEMACSDIR="${XDG_CONFIG_HOME}/spacemacs"
# mv ~/.spacemacs "$SPACEMACSDIR/init.el"

mkdir -p ${XDG_DATA_HOME}/vscode
export VSCODE_PORTABLE=${XDG_DATA_HOME}/vscode

#mkdir -p "${XDG_DATA_HOME}"/go
#export GOPATH="${XDG_DATA_HOME}"/go
#export GOROOT="/usr/local/go"
#export PATH="${GOPATH}/bin:${PATH}"

#mkdir -p "${XDG_DATA_HOME}/cargo" "${XDG_DATA_HOME}/rustup"
#export CARGO_HOME="${XDG_DATA_HOME}/cargo"
#export RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
#export PATH="${CARGO_HOME}/bin:${PATH}"

#mkdir -p "${XDG_CONFIG_HOME}/jupyter" "${XDG_CONFIG_HOME}/poetry"
#export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME}/jupyter"
#export IPYTHONDIR="${XDG_CONFIG_HOME}/jupyter"
#export POETRY_HOME="${XDG_CONFIG_HOME}/poetry"
# export PYTHONSTARTUP="${HOME}/python/pythonrc"

mkdir -p "${XDG_CONFIG_HOME}/npm" "${XDG_DATA_HOME}/node"
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm/npmrc"
export NODE_REPL_HISTORY="${XDG_DATA_HOME}/node/node_repl_history"
#export store-dir="${XDG_DATA_HOME}/pnpm-store"

if command -v mkcert >/dev/null 2>&1; then
    NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"
    export NODE_EXTRA_CA_CERTS
fi

#mkdir -p "${XDG_CONFIG_HOME}/java" "${XDG_CONFIG_HOME}/maven"
#export JAVA_HOME=""
#export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="${XDG_CONFIG_HOME}/java"
#mvn -gs "${XDG_CONFIG_HOME}/maven/settings.xml"

#mkdir -p "${XDG_DATA_HOME}/gem" "${XDG_CACHE_HOME}/gem"
#export GEM_HOME="${XDG_DATA_HOME}/gem"
#export GEM_SPEC_CACHE="${XDG_CACHE_HOME}/gem"

if command -v docker >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/docker" "${XDG_DATA_HOME}/docker/machine"
    export DOCKER_CONFIG="${XDG_CONFIG_HOME}/docker"
    export DOCKER_CONTEXT="default"
    export DOCKER_HOST="unix:///var/run/docker.sock"
    export MACHINE_STORAGE_PATH="${XDG_DATA_HOME}/docker/machine"
fi

#mkdir -p "${XDG_CONFIG_HOME}/pg" && mkdir -p "${XDG_CACHE_HOME}/pg"
#export PSQLRC="${XDG_CONFIG_HOME}/pg/psqlrc"
#export PGPASSFILE="${XDG_CONFIG_HOME}/pg/pgpass"
#export PGSERVICEFILE="${XDG_CONFIG_HOME}/pg/pg_service.conf"
#export PSQL_HISTORY="${XDG_CACHE_HOME}/pg/psql_history"

#mkdir -p "${XDG_CONFIG_HOME}/redis"
#export REDISCLI_HISTFILE="${XDG_DATA_HOME}/redis/rediscli_history"
#export REDISCLI_RCFILE="${XDG_CONFIG_HOME}/redis/redisclirc"

#mkdir -p "${XDG_DATA_HOME}/wineprefixes"
#export WINEPREFIX="${XDG_DATA_HOME}/wineprefixes/default"

#mkdir -p "${XDG_CONFIG_HOME}/android"
#export ANDROID_HOME="${HOME}/Library/Android/sdk"
#export ANDROID_USER_HOME="${XDG_CONFIG_HOME}/android"
# export PATH="${ANDROID_HOME}/bin:${PATH}"

mkdir -p ${XDG_CONFIG_HOME}/byobu
export BYOBU_CONFIG_DIR=${XDG_CONFIG_HOME}/byobu

mkdir -p ${XDG_CONFIG_HOME}/ipfs
export IPFS_PATH=${XDG_CONFIG_HOME}/ipfs

mkdir -p ${XDG_CACHE_HOME}/starship
export STARSHIP_CONFIG=${XDG_CONFIG_HOME}/starship.toml
export STARSHIP_CACHE=${XDG_CACHE_HOME}/starship

mkdir -p ${XDG_DATA_HOME}/z
export Z_DATA=${XDG_DATA_HOME}/z

mkdir -p ${XDG_CONFIG_HOME}/ffmpeg
export FFMPEG_DATADIR=${XDG_CONFIG_HOME}/ffmpeg
