#cloud-config

hostname: vm
users:
  - default
  - name: ubuntu
    groups: users,adm,sudo,ssl-cert,xrdp,input
    shell: /bin/bash
    lock_passwd: false
    passwd: ubuntu
    uid: 1001
    gid: 1234
    sudo: ALL=(ALL) NOPASSWD:ALL
    # ssh_authorized_keys:
    #   - ssh-rsa ABCDEF...
    # ssh_import_id:
    #   - github:username

ssh_pwauth: false

timezone: Asia/Tokyo
locale: ja_JP.utf8

package_update: true
package_upgrade: true
packages:
  # デスクトップ環境
  - xfce4
  - xfce4-goodies
  - xrdp

  # - ubuntu-desktop-minimal
  # - pulseaudio

  # - ubuntustudio-installer
  # - ubuntustudio-desktop
  # - ubuntustudio-audio
  # - ubuntustudio-audio-plugins
  # - ubuntustudio-video
  # - ubuntustudio-graphics

  # 日本語サポート
  - language-pack-ja-base
  - language-pack-ja
  - manpages-ja
  - fcitx5-mozc

  # 開発ツール
  - build-essential
  - cmake
  - libfuse2
  - libssl-dev
  - pkg-config
  - apt-transport-https
  - ca-certificates
  # - ruby
  - libinput-tools
  - libdb-dev
  - libdb5.3-dev
  - libgdbm-dev
  - libgmp-dev
  - libgmpxx4ldbl
  - libstd-rust-1.75
  - libstd-rust-dev
  - rustc
  - libncurses5-dev
  - libffi-dev
  - libgdbm-compat-dev

  # ユーティリティ
  - zsh
  - vim
  - gh
  - curl
  - wget
  - jq
  - gzip
  - tree
  - xsel
  - xdotool
  - ncdu
  - mkcert
  - moreutils
  - multitail
  - direnv
  - pwgen
  - gawk
  # - plank
  - neofetch

  # cargo系
  - lsd
  # - bat
  - zoxide
  - fzf

  # ネットワークツール
  - net-tools
  - nmap
  - wireshark
  # - netcat
  # - hashcat

  # マルチメディア
  - ffmpeg
  - mpd
  - mpc
  - ncmpcpp

  # Docker
  # - snapd
  # - docker
  # - docker.io
  # - docker-compose
  # - avahi-daemon

runcmd:
  - sudo sed -i 's/^s*REGDOMAIN=S*/REGDOMAIN=JP/' /etc/default/crda || true
  - LANG=C xdg-user-dirs-update --force
  - im-config -n fcitx5
  - sudo systemctl restart rsyslog
  - sudo dpkg --configure -a

  - sudo usermod -a -G ssl-cert,xrdp,input,audio
  - sudo ufw allow 3389
  - sudo systemctl enable xrdp
  - sudo systemctl start xrdp

keyboard:
  # 日本語キーボードの設定
  - model: pc105
  - layout: jp
  - options: ctrl:nocaps

# write_files:
#   # 環境変数の設定
#   - path: ~/.profile
#     content: |
#       #!/bin/sh

#       export XDG_CONFIG_HOME="$HOME/.config"
#       export XDG_CACHE_HOME="$HOME/.cache"
#       export XDG_DATA_HOME="$HOME/.local/share"
#       export XDG_STATE_HOME="$HOME/.local/state"

#       export TZ="Asia/Tokyo"
#       export LANG="ja_JP.UTF-8"
#       export LC_ALL="ja_JP.UTF-8"
#       export LC_CTYPE="en_US.UTF-8"
#       export TERM="screen-256color"
#       export EDITOR="vim"
#       export PS1="%N %n@%M %~ $ "

#       export PATH="$HOME/.local/bin:$PATH"
#     owner: root:root
#     permissions: '0755'

#   # LSD設定ファイル
#   - path: /home/ubuntu/.config/lsd/config.yaml
#     content: |
#       # LSD設定ファイル
#       color:
#         when: auto
#       icons:
#         when: auto
#       sorting:
#         dir-grouping: first
#     owner: ubuntu:ubuntu
#     permissions: '0644'
