config:
  security.nesting: "true"
  security.privileged: "true"
  user.user-data: |
    #cloud-config
    timezone: Asia/Tokyo
    locale: ja_JP.utf8
    hostname: vm
    users:
      - default
      - name: ubuntu
        passwd: ubuntu
        uid: 1001
        gid: 1001
        sudo: ALL=(ALL) ALL
        groups: [users,adm,staff,sudo]
        shell: /bin/bash
        ssh_authorized_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC9+qnJxEuf/eJrpeGWahUpYh38PVHt+X9nZslctV/en
    ssh_pwauth: false
    package_upgrade: true
    package_update: true
    packages:
      - openssh-server
      - gnupg
      - wget
      - zsh
      - sudo
      - curl
      - git
      - gh
      - vim
      - make
      - byobu
      - age
      - gnupg
      - jq
      - avahi-daemon
      - apt-transport-https
      - libssl-dev
      - build-essential
      - pkg-config
      - language-pack-ja-base
      - language-pack-ja
      - manpages-ja
    runcmd:
      - wget -q https://www.ubuntulinux.jp/ubuntu-ja-archive-keyring.gpg -O- | apt-key add -
      - wget -q https://www.ubuntulinux.jp/ubuntu-jp-ppa-keyring.gpg -O- | apt-key add -
      - wget https://www.ubuntulinux.jp/sources.list.d/focal.list -O /etc/apt/sources.list.d/ubuntu-ja.list
      - apt update -y
      - su -c 'sh -c "$(curl -fsSL get.chezmoi.io)" -- -b /usr/local/bin' ubuntu
      - git clone https://github.com/budybye/dotfiles.git ~/dotfiles
      - sudo systemctl daemon-reload
    write_files:
      - path: /etc/apt/sources.list.d/ubuntu-ja.list
        content: |
          deb http://ftp.jp.debian.org/debian/ focal main contrib non-free
description: "ubuntu xrdp"
devices: {}
name: vm
used_by: []
