config:
  security.nesting: "true"
  security.privileged: "true"
  user.user-data: |
    #cloud-config
    timezone: Asia/Tokyo
    locale: ja_JP.utf8
    hostname: vm
    users:
      - default
      - name: ubuntu
        passwd: ubuntu
        uid: 1001
        gid: 1001
        sudo: ALL=(ALL) ALL
        groups: [users,adm,staff,sudo]
        shell: /bin/bash
        home: /home/ubuntu
        ssh_authorized_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC9+qnJxEuf/eJrpeGWahUpYh38PVHt+X9nZslctV/en
    ssh_pwauth: false
    package_upgrade: true
    package_update: true
    packages:
      - openssh-server
      - gnupg
      - wget
      - zsh
      - sudo
      - curl
      - git
      - gh
      - vim
      - make
      - byobu
      - age
      - gnupg
      - jq
      - avahi-daemon
      - apt-transport-https
      - libssl-dev
      - build-essential
      - pkg-config
      - language-pack-ja-base
      - language-pack-ja
      - manpages-ja
      - xfce4
      - xfce4-goodies
      - xrdp
      - xorgxrdp
      - dbus-x11
    runcmd:
      - curl -fsSL get.chezmoi.io | sudo sh -s -- -b /usr/local/bin
      - git clone https://github.com/budybye/dotfiles.git /home/ubuntu/dotfiles
      - sudo systemctl enable xrdp
devices: {}
name: ubuntu
used_by: []
