config:
  security.nesting: "true"
  security.privileged: "true"
  user.user-data: |
    #cloud-config
    timezone: Asia/Tokyo
    locale: ja_JP.utf8
    package_upgrade: true
    package_update: true
    hostname: vm
    users:
      - name: ubuntu
        uid: 1001
        sudo: ALL=(ALL) ALL
        passwd: ubuntu
        shell: /bin/bash
        ssh_authorized_keys:
          - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC9+qnJxEuf/eJrpeGWahUpYh38PVHt+X9nZslctV/enルの中身>
description: "ubuntu xrdp"
devices: {}
name: vm
used_by: []
