config:
  security.nesting: "true"
  security.privileged: "true"
  user.user-data: |
    #cloud-config
    timezone: Asia/Tokyo
    locale: ja_JP.utf8
    hostname: vm
    fqdn: vm.local
    system_info:
      distro: ubuntu
      default_user:
        name: budybye
        passwd: budybye
        home: /home/budybye
        shell: /bin/bash
        sudo: ["ALL=(ALL) NOPASSWD:ALL"]
        groups: [users,adm,staff,sudo,ssl-cert,xrdp]
        lock_passwd: false
    groups: [users,adm,sudo,ssl-cert,xrdp]
    ssh_import_id:
      - gh:budybye
    ssh_pwauth: false
    package_upgrade: true
    package_update: true
    packages:
    - ssh-import-id
    - openssh-server
    - gnupg
    - wget
    - zsh
    - sudo
    - curl
    - git
    - gh
    - vim
    - make
    - byobu
    - age
    - gnupg
    - ufw
    - jq
    - avahi-daemon
    - apt-transport-https
    - libssl-dev
    - build-essential
    - pkg-config
    - language-pack-ja-base
    - language-pack-ja
    - manpages-ja
    - xfce4
    - xfce4-goodies
    - xrdp
    - xorgxrdp
    - dbus-x11
    runcmd:
    - curl -fsSL get.chezmoi.io | sudo sh -s -- -b /usr/local/bin
    - git clone https://github.com/budybye/dotfiles.git /home/budybye/dotfiles
    - echo "xfce4-session" > ~/.xsession
    - sudo update-alternatives --set x-session-manager /usr/bin/xfce4-session
    - sudo systemctl enable xrdp
devices: {}
name: ubuntu
used_by: []
