#cloud-config
hostname: vm
users:
  - default
  - name: ubuntu
    passwd: ubuntu
    uid: 1001
    gid: 1001
    shell: /bin/zsh
    groups: [users,adm,staff,sudo,docker]
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_import_id:
      - github:budybye
    lock_passwd: false

  - name: lisa
    passwd: lisa
    uid: 1024
    gid: 1024
    shell: /bin/zsh
    groups: [users,adm,staff,sudo,docker]
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_import_id:
      - github:budybye
    lock_passwd: false

ssh_pwauth: false
timezone: Asia/Tokyo
locale: ja_JP.utf8
keyboard:
  - model: pc105
  - layout: jp
  - options: ctrl:nocaps

package_update: true
package_upgrade: true
package_autoremove: true
package_cleanup: true
package_reboot_if_required: true
packages:
  - avahi-daemon
  - openssh-server
  - lsb-release
  - ca-certificates
  - git
  - curl
  - wget
  - make
  - zsh
  - jq
  - gh
  - age
  - vim
  - cmake
  - g++
  - gcc
  - gnupg
  - xsel
  - libssl-dev
  - pkg-config
  - apt-transport-https
  - build-essential
  - language-pack-ja-base
  - language-pack-ja
  - manpages-ja
runcmd:
  - curl -fsSL get.chezmoi.io | sh -s -- -b /home/ubuntu/.local/bin
