#cloud-config
hostname: vm
users:
  - default
  - name: ubuntu
    passwd: ubuntu
    uid: 1001
    gid: 1001
    shell: /usr/bin/zsh
    groups: users,adm,staff,sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC9+qnJxEuf/eJrpeGWahUpYh38PVHt+X9nZslctV/en
    lock_passwd: false

  - name: lisa
    passwd: lisa
    uid: 1024
    gid: 1024
    shell: /usr/bin/zsh
    groups: users,adm,staff,sudo
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_import_id:
      - github:budybye
    lock_passwd: false

ssh_pwauth: false
timezone: Asia/Tokyo
locale: ja_JP.utf8
keyboard:
  - model: pc105
  - layout: jp
  - options: ctrl:nocaps

package_update: true
package_upgrade: true
package_autoremove: true
package_cleanup: true
package_reboot_if_required: true
packages:
  - avahi-daemon
  - openssh-server
  - lsb-release
  - ca-certificates
  - git
  - curl
  - wget
  - make
  - zsh
  - jq
  - gh
  - age
  - vim
  - cmake
  - g++
  - gcc
  - gnupg
  - xsel
  - libssl-dev
  - pkg-config
  - apt-transport-https
  - build-essential
  - language-pack-ja-base
  - language-pack-ja
  - manpages-ja
  - xfce4
  - xfce4-goodies
  - xrdp
  - xorgxrdp
  - dbus-x11
runcmd:
  - curl -fsSL get.chezmoi.io | sudo sh -s -- -b /usr/local/bin
  - git clone https://github.com/budybye/dotfiles.git /home/ubuntu/dotfiles
  - sudo groupadd -f ssl-cert
  - sudo groupadd -f xrdp
  - sudo usermod -aG ssl-cert,xrdp ubuntu
  - echo "xfce4-session" > ~/.xsession
  - sudo update-alternatives --set x-session-manager /usr/bin/xfce4-session
  - sudo systemctl enable xrdp
