#!/usr/bin/env bash

# chsh -s /usr/bin/zsh

# 全体的にXDG BASED_DIRECTORYに設定する

HOSTNAME="$(uname -n)"
export HOSTNAME

if command -v dpkg >/dev/null 2>&1; then
    ARCH="$(dpkg --print-architecture)"
elif command -v uname >/dev/null 2>&1; then
    ARCH="$(uname -m)"
fi
export ARCH="${ARCH:-unknown}"

# パスを再設定
export PATH="${PATH}:${HOME}/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# ${VAR} "${VAR}" "${VAR:-var}" は環境変数
# ' : ' で区切り

# XDG DIRECTORY を作成して権限を700に設定
mkdir -p \
    "${HOME}/.local/share" \
    "${HOME}/.config" \
    "${HOME}/.local/state" \
    "${HOME}/.cache"
chmod 700 \
    "${HOME}/.config" \
    "${HOME}/.local/share" \
    "${HOME}/.local/state" \
    "${HOME}/.cache" \
    "${HOME}/.ssh"

# XDG DIRECTORY
export XDG_CONFIG_HOME=${HOME}/.config
export XDG_STATE_HOME=${HOME}/.local/state
export XDG_DATA_HOME=${HOME}/.local/share
export XDG_CACHE_HOME=${HOME}/.cache

export XDG_DATA_DIRS="${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
export XDG_CONFIG_DIRS="${XDG_CONFIG_DIRS:-/etc/xdg}"


# XDG_RUNTIME_DIR="/run/user/$(id -u)"
# export XDG_RUNTIME_DIR

mkdir -p \
    "${HOME}/Desktop" \
    "${HOME}/Downloads" \
    "${HOME}/Documents" \
    "${HOME}/Public" \
    "${HOME}/Music" \
    "${HOME}/Pictures" \
    "${HOME}/Movies" \
    "${HOME}/Templates"
export XDG_DESKTOP_DIR=${HOME}/Desktop
export XDG_DOWNLOAD_DIR=${HOME}/Downloads
export XDG_DOCUMENTS_DIR=${HOME}/Documents
export XDG_PUBLICSHARE_DIR=${HOME}/Public
export XDG_MUSIC_DIR=${HOME}/Music
export XDG_PICTURES_DIR=${HOME}/Pictures
export XDG_VIDEOS_DIR=${HOME}/Movies
export XDG_TEMPLATES_DIR=${HOME}/Templates

# export XDG_SESSION_TYPE=X11
# export XDG_SESSION_ID=1
# export DISPLAY=":0:${DISPLAY}"

export TZ="Asia/Tokyo"
export LANG="ja_JP.UTF-8"
export LC_ALL="ja_JP.UTF-8"
# TUIの表示乱れ防止
export LC_CTYPE="en_US.UTF-8"

export TMPDIR="/tmp"
export TERM="xterm-256color"

if command -v cursor >/dev/null 2>&1; then
    export EDITOR="cursor"
elif command -v code >/dev/null 2>&1; then
    export EDITOR="code"
elif command -v codium >/dev/null 2>&1; then
    export EDITOR="codium"
else
    export EDITOR="vim"
fi

if command -v brave-browser >/dev/null 2>&1; then
    export BROWSER="brave-browser"
fi

if command -v brew >/dev/null 2>&1; then
    export HOMEBREW_PREFIX="/opt/homebrew"
fi

if command -v mise >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/mise"
    export MISE_CONFIG_DIR="${XDG_CONFIG_HOME}/mise"
    touch "${MISE_CONFIG_DIR}/shorthands.toml"
    export MISE_SHORTHANDS_FILE="${MISE_CONFIG_DIR}/shorthands.toml"
    # miseディレクトリ全体のパーミッションを修正
    chmod -R 755 "${XDG_DATA_HOME}/mise/installs"
fi

if command -v aqua >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/aquaproj-aqua" "${XDG_DATA_HOME}/aquaproj-aqua"
    export PATH="${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua/bin:${PATH}"
    export AQUA_GLOBAL_CONFIG="${AQUA_GLOBAL_CONFIG:-}:${XDG_CONFIG_HOME:-$HOME/.config}/aquaproj-aqua/aqua.yaml"
fi

if command -v code >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/Code/user-data/User"
    export VSCODE_PORTABLE="${XDG_CONFIG_HOME}/Code"
    # export VSCODE_PORTABLE="${XDG_DATA_HOME}/Code"
fi

if command -v orb >/dev/null 2>&1; then
    source "${HOME}/.orbstack/shell/init.zsh" 2>/dev/null || :
    # docker context use orbstack >/dev/null
fi

if command -v docker >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/docker" "${XDG_DATA_HOME}/docker/machine"
    export MACHINE_STORAGE_PATH="${XDG_DATA_HOME}/docker/machine"
    export DOCKER_CONFIG="${XDG_CONFIG_HOME}/docker"

    if [ -f "${HOME}/.orbstack/docker.sock" ]; then
        export DOCKER_HOST="unix://${HOME}/.orbstack/docker.sock"
        export DOCKER_CONTEXT="orbstack"

    elif [ -f /var/run/docker.sock ]; then
        export DOCKER_HOST="unix:///var/run/docker.sock"
        export DOCKER_CONTEXT="default"

    elif [ -f "${HOME}/.docker/run/docker.sock" ]; then
        export DOCKER_HOST="unix://${HOME}/.docker/run/docker.sock"
        export DOCKER_CONTEXT="desktop-linux"
    fi
elif command -v podman >/dev/null 2>&1; then
    PODMAN_SOCKET=`podman machine inspect --format '{{ .ConnectionInfo.SocketPath }}'`
    export DOCKER_HOST="unix://${PODMAN_SOCKET}"
    export DOCKER_CONTEXT="podman-machine-default"
    export DOCKER_BUILDKIT=0
fi

if command -v npm >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/npm" "${XDG_DATA_HOME}/node"
    export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME}/npm/npmrc"
    export NODE_REPL_HISTORY="${XDG_DATA_HOME}/node/node_repl_history"
fi

if command -v pnpm >/dev/null 2>&1; then
    mkdir -p "${XDG_DATA_HOME}/pnpm"
    export PNPM_HOME="${XDG_DATA_HOME}/pnpm"
    export store-dir="${XDG_DATA_HOME}/pnpm-store"
fi

if command -v bun >/dev/null 2>&1; then
    mkdir -p "${XDG_DATA_HOME}/bun"
    export BUN_INSTALL="${XDG_DATA_HOME}/bun"
fi

if command -v mkcert >/dev/null 2>&1 && [ -f "$(mkcert -CAROOT)/rootCA.pem" ]; then
    NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"
    export NODE_EXTRA_CA_CERTS
fi

if command -v gpg >/dev/null 2>&1; then
    mkdir -p "${XDG_DATA_HOME}/gnupg"
    export GNUPGHOME="${XDG_DATA_HOME}/gnupg"
fi

if command -v go >/dev/null 2>&1; then
    mkdir -p "${XDG_DATA_HOME}/go" "${XDG_CACHE_HOME}/go/mod"
    export GOPATH="${XDG_DATA_HOME}/go"
    # export GOPATH="${HOME}/.go"
    export GOROOT="${GOPATH}"
    export GOMODCACHE="${XDG_CACHE_HOME}/go/mod"
    export GOCACHE="${XDG_CACHE_HOME}/go/go-build"
    export PATH="${GOPATH}/bin:${PATH}"
fi

if command -v cargo >/dev/null 2>&1; then
    mkdir -p "${XDG_DATA_HOME}/cargo" "${XDG_DATA_HOME}/rustup"
    export CARGO_HOME="${XDG_DATA_HOME}/cargo"
    # export CARGO_HOME="${HOME}/.cargo"
    export RUSTUP_HOME="${XDG_DATA_HOME}/rustup"
    export PATH="${CARGO_HOME}/bin:${PATH}"
fi

if command -v gem >/dev/null 2>&1; then
    mkdir -p "${XDG_DATA_HOME}/gem" "${XDG_CACHE_HOME}/gem"
    export GEM_HOME="${XDG_DATA_HOME}/gem"
    export GEM_SPEC_CACHE="${XDG_CACHE_HOME}/gem"
fi

if command -v python3 >/dev/null 2>&1; then
    mkdir -p "${XDG_DATA_HOME}/python" "${XDG_CACHE_HOME}/python" "${XDG_CONFIG_HOME}/python" "${XDG_STATE_HOME}/python"
    export PYTHONUSERBASE="${XDG_DATA_HOME}/python"
    export PYTHONHISTORY="${XDG_STATE_HOME}/python/history"
    export PYTHONPYCACHEPREFIX="${XDG_CACHE_HOME}/python"
    export PYTHONSTARTUP="${XDG_CONFIG_HOME}/python/pythonrc"
fi

if command -v poetry >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/poetry" "${XDG_CACHE_HOME}/poetry"
    export POETRY_HOME="${XDG_CONFIG_HOME}/poetry"
    export POETRY_CACHE="${XDG_CACHE_HOME}/poetry"
    export POETRY_VIRTUALENVS_IN_PROJECT=true
fi

if command -v jupyter >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/jupyter"
    export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME}/jupyter"
    export IPYTHONDIR="${XDG_CONFIG_HOME}/jupyter"
fi

if command -v java >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/java" "${XDG_DATA_HOME}/java"
    export JAVA_HOME="${XDG_DATA_HOME}/java"
    export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=${XDG_CONFIG_HOME}/java"
fi

if command -v mvn >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/maven"
    export MAVEN_HOME="${XDG_CONFIG_HOME}/maven"
    export MAVEN_CONFIG="${XDG_CONFIG_HOME}/maven"
    mvn -gs "${XDG_CONFIG_HOME}/maven/settings.xml"
fi

if command -v psql >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/pg" "${XDG_CACHE_HOME}/pg"
    export PSQLRC="${XDG_CONFIG_HOME}/pg/psqlrc"
    export PGPASSFILE="${XDG_CONFIG_HOME}/pg/pgpass"
    export PGSERVICEFILE="${XDG_CONFIG_HOME}/pg/pg_service.conf"
    export PSQL_HISTORY="${XDG_CACHE_HOME}/pg/psql_history"
fi

if command -v redis-cli >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/redis" "${XDG_DATA_HOME}/redis"
    export REDISCLI_HISTFILE="${XDG_DATA_HOME}/redis/rediscli_history"
    export REDISCLI_RCFILE="${XDG_CONFIG_HOME}/redis/redisclirc"
fi

if command -v wine >/dev/null 2>&1; then
    mkdir -p "${XDG_DATA_HOME}/wineprefixes"
    export WINEPREFIX="${XDG_DATA_HOME}/wineprefixes/default"
fi

# if command -v android >/dev/null 2>&1; then
#     mkdir -p "${XDG_CONFIG_HOME}/android"
#     export ANDROID_HOME="${HOME}/Library/Android/sdk"
#     # export ANDROID_USER_HOME="${XDG_CONFIG_HOME}/android"
#     export PATH="${ANDROID_HOME}/bin:${PATH}"
# fi

if command -v vim >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/vim" "${XDG_CONFIG_HOME}/nvim"
    # export VIMINIT='let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc" | source $MYVIMRC'
    export VIMINIT='let $MYVIMRC = !has("nvim") ? "${XDG_CONFIG_HOME}/vim/vimrc" : "${XDG_CONFIG_HOME}/nvim/init.vim" | source $MYVIMRC'
fi

if command -v spacemacs >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/spacemacs"
    export SPACEMACSDIR="${XDG_CONFIG_HOME}/spacemacs"
    if [ -f "${HOME}/.spacemacs" ]; then
        mv "${HOME}/.spacemacs" "${SPACEMACSDIR}/init.el"
    fi
fi

if command -v byobu >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/byobu"
    export BYOBU_CONFIG_DIR="${XDG_CONFIG_HOME}/byobu"
fi

if command -v ipfs >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/ipfs"
    export IPFS_PATH="${XDG_CONFIG_HOME}/ipfs"
fi

if command -v starship >/dev/null 2>&1; then
    mkdir -p "${XDG_CACHE_HOME}/starship"
    export STARSHIP_CONFIG="${XDG_CONFIG_HOME}/starship.toml"
    export STARSHIP_CACHE="${XDG_CACHE_HOME}/starship"
fi

if command -v zoxide >/dev/null 2>&1; then
    mkdir -p "${XDG_DATA_HOME}/z"
    export Z_DATA="${XDG_DATA_HOME}/z"
fi

if command -v rg >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/ripgrep"
    export RIPGREP_CONFIG_PATH="${XDG_CONFIG_HOME}/ripgrep/config"
fi

if command -v ffmpeg >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/ffmpeg"
    export FFMPEG_DATADIR="${XDG_CONFIG_HOME}/ffmpeg"
fi

if command -v kubectl >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/kube" "${XDG_CACHE_HOME}/kube"
    export KUBECONFIG="${XDG_CONFIG_HOME}/kube"
    export KUBECACHEDIR="${XDG_CACHE_HOME}/kube"
fi

if command -v minikube >/dev/null 2>&1; then
    mkdir -p "${XDG_DATA_HOME}/minikube"
    export MINIKUBE_HOME="${XDG_DATA_HOME}/minikube"
fi

if command -v conan >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/conan"
    export CONAN_USER_HOME="${XDG_CONFIG_HOME}/conan"
fi

# if [ "${XDG_SESSION_TYPE}" = "x11" ]; then
#     mkdir -p "${XDG_CACHE_HOME}/x11" "${XDG_CONFIG_HOME}/x11"
#     export USERXSESSION="${XDG_CACHE_HOME}/x11/xsession"
#     export USERXSESSIONRC="${XDG_CONFIG_HOME}/x11/xsessionrc"
#     export ALTUSERXSESSION="${XDG_CACHE_HOME}/x11/Xsession"
#     export ERRFILE="${XDG_CACHE_HOME}/x11/xsession-errors"
#     export XINITRC="${XDG_CONFIG_HOME}/x11/xinitrc"
#     export XSERVERRC="${XDG_CONFIG_HOME}/x11/xserverrc"
#     export ICEAUTHORITY="${XDG_CACHE_HOME}/ICEauthority"
# fi

# if [ -f "${HOME}/.Xauthority" ]; then
    # mkdir -p "${XDG_RUNTIME_DIR}/Xauthority"
    # export XAUTHORITY="${XDG_RUNTIME_DIR}/Xauthority"
    # mv "${HOME}/.Xauthority" "${XDG_RUNTIME_DIR}/Xauthority"
# fi

if command -v discord >/dev/null 2>&1; then
    mkdir -p "${XDG_DATA_HOME}/discord"
    export DISCORD_USER_DATA_DIR="${XDG_DATA_HOME}/discord"
fi

if command -v htop >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/htop"
    if [ -f "${HOME}/.htoprc" ]; then
        cp "${HOME}/.htoprc" "${XDG_CONFIG_HOME}/htop/htoprc"
    fi
fi

if command -v curl >/dev/null 2>&1; then
    if [ -f "${HOME}/.curlrc" ]; then
        cp "${HOME}/.curlrc" "${XDG_CONFIG_HOME}/.curlrc"
    fi
fi

if command -v mpd >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/mpd/playlists"
    touch "${XDG_CONFIG_HOME}/mpd/mpd.db"
    touch "${XDG_CONFIG_HOME}/mpd/mpd.log"
    touch "${XDG_CONFIG_HOME}/mpd/mpd.pid"
    touch "${XDG_CONFIG_HOME}/mpd/mpdstate"
    export MPD_HOST="127.0.0.1"
    export MPD_PORT="6600"
fi

if command -v ncmpcpp >/dev/null 2>&1; then
    mkdir -p "${XDG_CONFIG_HOME}/ncmpcpp/lyrics"
    export NCMPCPP_CONFIG_DIR="${XDG_CONFIG_HOME}/ncmpcpp"
fi
