[font]
size = 13

[font.normal]
family = "HackGen Console NF"
style = "Regular"

[font.bold]
family = "HackGen Console NF"
style = "Bold"

[font.italic]
family = "HackGen Console NF"
style = "Italic"

[shell]
program = "/bin/zsh"
args = ["--login"]

[window]
opacity = 0.78
decorations = "full"

[window.padding]
x = 4
y = 2

[scrolling]
history = 10000

[colors.primary]
background = "0x272822"
foreground = "0xf8f8f2"

[colors.normal]
black = "0x272822"
red = "0xf92672"
green = "0xa6e22e"
yellow = "0xe6db74"
blue = "0xae81ff"
magenta = "0xfd971f"
cyan = "0x66d9ef"
white = "0xf8f8f2"

[colors.bright]
black = "0x4c4c4c"
red = "0xf43753"
green = "0xc9d05c"
yellow = "0xffc24b"
blue = "0xb3deef"
magenta = "0xd3b987"
cyan = "0x73cef4"
white = "0xfeffff"
