import type { ModelDef } from "./types";

export const BUILT_IN_MODELS: ModelDef[] = [
  {
    id: "openai/gpt-5.5-2026-04-23",
    name: "GPT-5.5 (2026-04-23)",
    provider: "openai",
    contextWindow: 256000,
    maxTokens: 32768,
    input: ["text", "image"],
    zdrSupported: true,
    cost: { input: 100, output: 200, cacheRead: 50, cacheWrite: 100 },
    compat: { supportsDeveloperRole: true, maxTokensField: "max_tokens" },
  },
  {
    id: "openai/gpt-4.5-preview",
    name: "GPT-4.5 Preview",
    provider: "openai",
    contextWindow: 128000,
    maxTokens: 16384,
    input: ["text", "image"],
    zdrSupported: true,
    cost: { input: 75, output: 150, cacheRead: 37.5, cacheWrite: 75 },
    compat: { supportsDeveloperRole: true, maxTokensField: "max_tokens" },
  },
  {
    id: "openai/gpt-4o",
    name: "GPT-4o",
    provider: "openai",
    contextWindow: 128000,
    maxTokens: 16384,
    input: ["text", "image"],
    zdrSupported: true,
    cost: { input: 2.5, output: 10, cacheRead: 1.25, cacheWrite: 5 },
    compat: { supportsDeveloperRole: true, maxTokensField: "max_tokens" },
  },
  {
    id: "openai/gpt-5-nano-2025-08-07",
    name: "GPT-5 Nano (2025-08-07)",
    provider: "openai",
    contextWindow: 128000,
    maxTokens: 16384,
    input: ["text", "image"],
    zdrSupported: true,
    cost: { input: 1, output: 5, cacheRead: 0.5, cacheWrite: 1 },
    compat: { supportsDeveloperRole: true, maxTokensField: "max_tokens" },
  },
  {
    id: "anthropic/claude-opus-4-7",
    name: "Claude Opus 4-7",
    provider: "anthropic",
    contextWindow: 200000,
    maxTokens: 4096,
    input: ["text", "image"],
    zdrSupported: true,
    cost: { input: 15, output: 75 },
    compat: { supportsDeveloperRole: false, maxTokensField: "max_tokens" },
  },
  {
    id: "anthropic/claude-sonnet-4-6",
    name: "Claude Sonnet 4-6",
    provider: "anthropic",
    contextWindow: 200000,
    maxTokens: 8192,
    input: ["text", "image"],
    zdrSupported: true,
    cost: { input: 3, output: 15 },
    compat: { supportsDeveloperRole: false, maxTokensField: "max_tokens" },
  },
  {
    id: "anthropic/claude-3-5-haiku-20241022",
    name: "Claude 3.5 Haiku (2024-10-22)",
    provider: "anthropic",
    contextWindow: 200000,
    maxTokens: 8192,
    input: ["text", "image"],
    zdrSupported: true,
    cost: { input: 0.8, output: 4 },
    compat: { supportsDeveloperRole: false, maxTokensField: "max_tokens" },
  },
  {
    id: "google/gemini-2.5-pro-preview-03-25",
    name: "Gemini 2.5 Pro",
    provider: "google",
    contextWindow: 1000000,
    maxTokens: 8192,
    input: ["text", "image"],
    zdrSupported: false,
    cost: { input: 1.25, output: 10 },
    compat: { supportsDeveloperRole: false, maxTokensField: "max_tokens" },
  },
  {
    id: "google/gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    provider: "google",
    contextWindow: 1000000,
    maxTokens: 8192,
    input: ["text", "image"],
    zdrSupported: false,
    cost: { input: 0.1, output: 0.4 },
    compat: { supportsDeveloperRole: false, maxTokensField: "max_tokens" },
  },
];
