name: ubuntu
services:

  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ghcr.io/budybye/ubuntu-dev:main
    container_name: ubuntu
    hostname: docker
    privileged: true
    platform: linux/${ARCH:-$(dpkg --print-architecture || uname -m)}
    ports:
    - ${RDP_PORT:-33389}:3389 # 127.1:33389 で RDP
    - ${SSH_PORT:-2222}:22
    # volumes:
    #   - ${HOME}/data:/home/ubuntu/data
    environment:
      REMOTE_CONTAINERS: true
      MISE_GITHUB_TOKEN: ${MISE_GITHUB_TOKEN:-}
    shm_size: 512m # ブラウザ対策
    # entrypoint: ["entrypoint"]
    command: ["ubuntu", "ubuntu", "yes"]
    tty: true
    restart: always

  tunnel:
    image: cloudflare/cloudflared
    command: tunnel run --token ${TUNNEL_TOKEN:-}
    restart: unless-stopped
    extra_hosts: ["host.docker.internal:host-gateway"]
