name: dev
services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER: dev
        UID: 1024
    # image: ghcr.io/budybye/ubuntu-dev:main
    container_name: ubuntu
    hostname: docker
    privileged: true
    environment:
      - DOCKER=true
    #   - REMOTE_CONTAINERS=true
    platform: linux/${ARCH:-$(dpkg --print-architecture || uname -m)}
    networks:
      - v4
      - v6
    ports:
      - 33389:3389 # 127.0.0.1:33389 で RDP
      - 2222:22
    volumes:
      - ${HOME}/data:/home/ubuntu/data
    shm_size: 512m # ブラウザ対策
    command: ["ubuntu", "ubuntu", "yes"] # user, password, sudo-no-passwd
    tty: true

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    networks:
      - v4
      - v6
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443 # https://localhost:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    restart: always

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - v4
      - v6
    command:
      - tunnel
      - run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN:-}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ipfs:
    image: ipfs/kubo
    container_name: ipfs
    networks:
      - v4
      - v6
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001 # http://localhost:5001/webui
    environment:
      IPFS_PROFILE: server # server modeで起動
    command: daemon
    volumes:
      - ./ipfs:/data/ipfs
    restart: unless-stopped

networks:
  v4:
    name: main
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/8
  v6:
    name: sub
    driver: bridge
    ipam:
      config:
        - subnet: fffe:1234:ccdd::/32

volumes:
  dev_data:
