services:

  ubuntu:
    image: ghcr.io/budybye/ubuntu-dev:main-slim
    container_name: ubuntu
    privileged: true
    networks:
      - local
    ports:
      - 3389:3389 # RDP
    tty: true

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    networks:
      - local
    ports:
      - 8000:8000
      - 9443:9443 # https://localhost:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    restart: always

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - local
    command:
      - tunnel
      - run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ipfs:
    image: ipfs/kubo
    container_name: ipfs
    networks:
      - local
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001 # http://localhost:5001/webui
    environment:
      IPFS_PROFILE: server # server modeで起動
    command: daemon
    volumes:
      - ./ipfs:/data/ipfs
    restart: unless-stopped

networks:
  local:
    driver: bridge

volumes:
  dev_data:
