services:

  ubuntu:
    # image: ghcr.io/dotfiles/ubuntu-rdp:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu
    networks:
      - app-network
    ports:
      - "8787:80"
      - "3389:3389"
    environment:
      - ENV=production
    # command: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply budybye

  ipfs:
    image: ipfs/kubo
    container_name: ipfs
    networks:
      - app-network
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001 # http://localhost:5001/webui
    volumes:
      # ipfsの設定ファイルをマウント
      - ./dev/ipfs:/home/ubuntu/.config/ipfs
      # ipfsのエクスポートファイルをマウント
      - ./dev/ipfs:/export
      #init直後のdaemon起動前に実行されるshをマウント
      - ./dev/ipfs/entrypoint.sh:/container-init.d/entrypoint.sh
    environment:
      IPFS_PROFILE: server # server modeで起動
      IPFS_PATH: /home/ubuntu/.config/ipfs
    # command: ipfs daemon
    restart: always

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    networks:
      - app-network
    ports:
      - 8000:8000
      - 9443:9443 # http://localhost:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./dev/portainer:/data
    restart: always

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./dev/cloudflared:/home/nonroot/.cloudflared
    command: tunnel --url http://portainer:9443

networks:
  app-network:
    driver: bridge
