services:

  ubuntu:
    image: ghcr.io/budybye/ubuntu-dev:main
    privileged: true
    networks:
      - app-network
    ports:
      - 3389:3389 # RDP
    # environment:
      # - ENV=production
    command: chezmoi help
    tty: true

  ipfs:
    image: ipfs/kubo
    networks:
      - app-network
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001 # http://localhost:5001/webui
    environment:
      IPFS_PROFILE: server # server modeで起動
    command: ipfs daemon
    volumes:
      - /ipfs:/data/ipfs
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce
    networks:
      - app-network
    ports:
      - 8000:8000
      - 9443:9443 # http://localhost:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    restart: always

  cloudflared:
    image: cloudflare/cloudflared
    networks:
      - app-network
    command: tunnel --url http://portainer:9443
    restart: unless-stopped
    depends_on:
      - portainer

networks:
  default:
    external: true
  app-network:
    driver: bridge
