services:

  ubuntu:
    image: ghcr.io/budybye/ubuntu-dev:main
    container_name: ubuntu
    privileged: true
    networks:
      local:
        ipv4_address: 10.10.10.13
        ipv6_address: 2001:db8:1:1::13
    ports:
      - 3389:3389 # RDP
    # environment:
      # - ENV=production
    command: chezmoi help
    tty: true

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    networks:
      local:
        ipv4_address: 10.10.10.11
        ipv6_address: 2001:db8:1:11
    ports:
      - 8000:8000
      - 9443:9443 # http://localhost:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    restart: always

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    networks:
      local:
        ipv4_address: 10.10.10.12
        ipv6_address: 2001:db8:1:1::12
    command: tunnel --url http://portainer:9443
    restart: unless-stopped
    depends_on:
      - portainer

  ipfs:
    image: ipfs/kubo
    container_name: ipfs
    networks:
      local:
        ipv4_address: 10.10.10.10
        ipv6_address: 2001:db8:1:1::10
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001 # http://localhost:5001/webui
    environment:
      IPFS_PROFILE: server # server modeで起動
    command: ipfs daemon
    volumes:
      - /ipfs:/data/ipfs
    restart: unless-stopped

networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1
        - subnet: 2001:db8:1:1::/64
          gateway: 2001:db8:1:1::1
  # default:
  #   external: true
