services:

  ubuntu:
    image: ghcr.io/budybye/ubuntu-dev:main
    container_name: ubuntu
    networks:
      - app-network
    ports:
      - 8787:80
      - 3389:3389 # RDP
    # environment:
      # - ENV=production
    command: |
      - /bin/sh
      - -c
      - "while true; do sleep 1000; done"
    tty: true

  ipfs:
    image: ipfs/kubo
    container_name: ipfs
    networks:
      - app-network
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001 # http://localhost:5001/webui
    environment:
      IPFS_PROFILE: server # server modeで起動
    restart: always

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    networks:
      - app-network
    ports:
      - 8000:8000
      - 9443:9443 # http://localhost:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    restart: always

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    networks:
      - app-network
    command: tunnel --url http://portainer:9443
    restart: unless-stopped
    depends_on:
      - portainer

networks:
  app-network:
    driver: bridge
