name: dev
services:
  # docker-compose up -d --build ubuntu ipfs cloudflared portainer
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    # image: ghcr.io/budybye/ubuntu-dev:main
    container_name: ubuntu
    hostname: docker
    privileged: true
    platform: linux/${ARCH:-$(dpkg --print-architecture || uname -m)}
    networks:
      - v4
      # - v6
    ports:
      - 33389:3389 # RDP
      - 2222:22 # SSH
    command: ["ubuntu", "ubuntu", "yes"]
    tty: true
  # docker コマンドだと
  # docker run -rm
  # --interactive --tty
  # --privileged
  # --platform linux/${ARCH}
  # --network main --network sub
  # --name ubuntu
  # -p 33389:3389 -p 2222:22
  # ghcr.io/budybye/ubuntu-dev:main
  # ubuntu ubuntu yes
  #
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    networks:
      - v4
      # - v6
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443 # https://localhost:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    restart: always

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    restart: unless-stopped
    networks:
      - v4
      # - v6
    command:
      - tunnel
      - run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN:-}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ipfs:
    image: ipfs/kubo
    container_name: ipfs
    networks:
      - v4
      # - v6
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001 # http://localhost:5001/webui
    environment:
      IPFS_PROFILE: server # server modeで起動
    command: daemon
    volumes:
      - ./ipfs:/data/ipfs
    restart: unless-stopped

networks:
  v4:
    name: main
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/8
  # v6:
  #   name: sub
  #   driver: bridge
  #   ipam:
  #     config:
  #       - subnet: fffe:1234:ccdd::/32

volumes:
  dev_data:
