services:

  ubuntu:
    image: ghcr.io/budybye/ubuntu-dev:main-desktop
    container_name: ubuntu
    privileged: true
    networks:
      local:
        ipv4_address: 10.10.10.13
        ipv6_address: aaaa:bbbb:cccc:dddd:eeee:13
    ports:
      - 3389:3389 # RDP
    command: git clone https://github.com/budybye/dotfiles.git
    tty: true

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    networks:
      local:
        ipv4_address: 10.10.10.11
        ipv6_address: aaaa:bbbb:cccc:dddd:eeee:11
    ports:
      - 8000:8000
      - 9443:9443 # https://localhost:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer:/data
    restart: always

  tunnel-portainer:
    image: cloudflare/cloudflared
    container_name: tunnel-portainer
    networks:
      local:
        ipv4_address: 10.10.10.12
        ipv6_address: aaaa:bbbb:cccc:dddd:eeee:12
    command: tunnel --url https://portainer:9443
    restart: unless-stopped
    depends_on:
      - portainer

  tunnel-ipfs:
    image: cloudflare/cloudflared
    container_name: tunnel-ipfs
    networks:
      local:
        ipv4_address: 10.10.10.14
        ipv6_address: aaaa:bbbb:cccc:dddd:eeee:14
    command: tunnel --url http://ipfs:5001
    restart: unless-stopped
    depends_on:
      - ipfs

  ipfs:
    image: ipfs/kubo
    container_name: ipfs
    networks:
      local:
        ipv4_address: 10.10.10.10
        ipv6_address: aaaa:bbbb:cccc:dddd:eeee:10
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001 # http://localhost:5001/webui
    environment:
      IPFS_PROFILE: server # server modeで起動
    command: config --json API.HTTPHeaders.Access-Control-Allow-Origin '["*"]'
    volumes:
      - /ipfs:/data/ipfs
    restart: unless-stopped

networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1
        - subnet: aaaa:bbbb:cccc:dddd:eeee:/64
          gateway: aaaa:bbbb:cccc:dddd:eeee:1
  # default:
  #   external: true
