[tools]
# go = "latest"
bun = "latest"
node = "latest"
pnpm = "latest"
# rust = "latest"
python = "latest"
poetry = "latest"
java = "latest"
# ruby = "latest"
# php = "latest"
maven = "latest"

terraform = "latest"
# chezmoi = "latest"
bitwarden = "latest"
sqlite = "latest"
websocat = "latest"
# mkcert = "latest"
# direnv = "latest"
