# https://starship.rs/ja-jp/config/

"$schema" = 'https://starship.rs/config-schema.json'

# シェルプロンプトの間に空行を追加します
add_newline = true

# タイムアウト時間
scan_timeout = 420

# コマンドタイムアウト
command_timeout = 4422

# カラーパレットの定義
palette = 'color'

# 継続プロンプトの表示
# continuation_prompt = "▶▶"

# 並び順
format = """
[ ](gray)\
[░▒▓](gray)\
$os\
$username\
$hostname\
[](fg:gray bg:navy)\
$directory\
[](fg:navy bg:dark)\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
[](fg:dark bg:dd)\
$fill\
$nodejs\
$rust\
$golang\
$php\
$java\
$python\
$ruby\
$bun\
$package\
[](fg:dd bg:ddd)\
$time\
$battery\
$memory_usage\
[](fg:ddd bg:ddd)\
$cmd_duration\
[](fg:ddd)\
$line_break\
$character\
$localip\
$docker_context\
$custom\
$shell\
"""

# right_format = """
# $cmd_duration
# $time
# """

# 色の設定
[palettes.color]
# Kanagawa Dragon
gray = '#a6a69c'    # dragonGray
white = '#c5c9c5'   # dragonWhite
navy = '#8ba4b0'    # dragonBlue2
dark = '#8992a7'    # dragonViolet
dd = '#181616'      # dragonBlack3
ddd = '#12120f'     # dragonBlack1
red = '#c4746e'     # dragonRed
green = '#87a987'   # dragonGreen
yellow = '#b6927b'  # dragonOrange
blue = '#8ea4a2'    # dragonAqua

[os]
disabled = false
style = "fg:dd bg:gray"

[os.symbols]
Windows = " "
Ubuntu = " "
Linux = " "
Macos = " "
Raspbian = " "
RedHatEnterprise = " "

# ユーザー名
[username]
style_user = "fg:dd bg:gray"
style_root = "fg:red bg:gray"
format = '[($user)@]($style bold)'
disabled = false
show_always = true

# ホスト名
[hostname]
ssh_only = false
style = "fg:dd bg:gray"
format = '[$ssh_symbol$hostname:]($style bold)'
disabled = false

[directory]
style = "fg:dd bg:navy"
format = "[ $path]($style bold)"
truncate_to_repo = false
truncation_length = 5
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = "  "
"Music" = "  "
"Pictures" = "  "

[git_branch]
symbol = " "
style = "fg:dd bg:dark"
format = '[ $symbol $branch ]($style bold)'

[git_status]
style = "fg:dd bg:dark"
format = '[($all_status$ahead_behind)]($style bold)'
conflicted = "💥 "
ahead = "🏎💨 "
behind = "😰 "
diverged = "😵 "
untracked = "🌚 "
stashed = "📦 "
modified = "📝 "
staged = '🔦 '
renamed = "🏷 "
deleted = "🗑 "

[nodejs]
symbol = " "
style = "fg:gray bg:dd"
format = '[ $symbol($version)]($style bold)'

[rust]
symbol = " "
style = "fg:gray bg:dd"
format = '[ $symbol($version)]($style bold)'

[golang]
symbol = "ﳑ "
style = "fg:gray bg:dd"
format = '[ $symbol($version)]($style bold)'

[php]
symbol = " "
style = "fg:gray bg:dd"
format = '[ $symbol($version)]($style bold)'

[java]
symbol = '🌟 '
style = "fg:gray bg:dd"
format = '[ $symbol($version)]($style bold)'

[python]
symbol = ' '
style = "fg:gray bg:dd"
format = '[ $symbol($version)]($style bold)'

[ruby]
symbol = ' '
style = "fg:gray bg:dd"
format = '[ $symbol($version)]($style bold)'

[bun]
symbol = '🍞 '
style = "fg:gray bg:dd"
format = '[ $symbol($version)]($style bold)'

[package]
symbol = " "
style = "fg:gray bg:dd"
format = '[ $symbol($version)]($style bold)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:gray bg:ddd"
format = '[ $time]($style bold)'

# バッテリー表示
[battery]
full_symbol = ' '
charging_symbol = ' '
discharging_symbol = '⚠️ '
disabled = false
format = '[ $symbol$percentage]($style bold)'

# バッテリーを表示するタイミング、表示する際の文字の色する際の文字の色
[[battery.display]]
threshold = 101
style = "fg:gray bg:ddd"

[memory_usage]
disabled = false
threshold = -1
symbol = " "
style = "fg:gray bg:ddd"
format = '[ $symbol${ram_pct}]($style bold)'

[cmd_duration]
style = "fg:navy bg:ddd"
min_time = 4200
format = '[$duration]($style bold)'

# IPアドレス
[localip]
ssh_only = true
style = "fg:dd bg:gray"
format = '[@$localipv4]($style bold) '
disabled = false

[docker_context]
format = "[🐋$context](fg:blue bold) "

[character]
success_symbol = "[♨︎ ](fg:green bold)"
error_symbol = "[♨︎ ](fg:red bold)"

[shell]
fish_indicator = ' '
powershell_indicator = '_ '
style = 'fg:green'
# format = '[$indicator](strikethrough fg:red bold) [kush]($style bold) [](fg:yellow bold) '
format = '[$indicator](fg:green bold) [](fg:yellow bold) '
#format = '[$indicator\$]($style bold) '
disabled = false

# x86 or arm64
[custom.arch]
command = "uname -m"
when = """ test $(uname -m) = "x86_64" """
style = "bold gray"
format = "[$output]($style bold) "

[gcloud]
disabled = true
