name: Date
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo ${{ inputs.version }}
          echo ${{ github.ref_name }}
          echo ${{ env.new_tag }}
          date
