name: Date
on:
  workflow_call:
    inputs:
      version:
        type: string

jobs:
  date:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo ${{ inputs.version }}
          date
