name: Docker Image CI

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: docker-ubuntu-xfce-xrdp-jp

jobs:

  docker-build-push-compose:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platforms}}
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

      - name: docker compose test
        run: |
          docker compose up -d
          docker logs ipfs
          docker ps -a
          docker compose down

  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chezmoi init
        run: |
          sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .

      - name: mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          mise use go

      - name: cargo
        run: |
          cargo install starship sheldon bat

      - name: gem
        run: |
          sudo gem i fusuma

      - name: go
        run: |
          go --version

  mac-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: chezmoi init
        run: |
          sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .

      - name: mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          mise use bun

      - name: bun
        run: |
          bun i -g wrangler
          echo "$HOME/.local/bin"

      - name: homebrew
        run: |
          . ./script/install.sh

      - name: default cmd
        run: |
          . ./script/defaults.sh
