name: Docker Image CI

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: duxx

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

      - name: compose test
        run: |
          docker compose up -d
          docker compose down

  macos-test:
    runs-on: macos-latest
    timeout-minutes: 10
    
    steps:
      - uses: actions/checkout@v4

      - name: Install chezmoi
        run: sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .
