name: Docker Image CI

on:
  push:
    branches: ["main"]

env:
  IMAGE_NAME: docker-ubuntu-xfce-xrdp-jp

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platforms}}
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}

      - name: docker compose test
        run: |
          docker compose up -d
          docker ps
          docker compose down

      - name: chezmoi init
        run: |
          sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .
          chezmoi doctor

      - name: mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          mise use node
          mise dr

  macos-test:
    runs-on: macos-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: chezmoi init
        run: |
          sh -c "$(curl -fsLS chezmoi.io/get)" -- init --apply -S .

      - name: mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
          mise use bun
          mise dr
