name: Ipfs Pinning
# mainブランチにpushされたら ipfsにピン留めする
on:
  push:
    branches:
      - main

jobs:
  ipfs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0

      - name: create bare clone
        run: |
          git clone --mirror https://github.com/budybye/dotfiles.git dotfiles
          cd dotfiles
          git update-server-info
          mv objects/pack/*.pack .
          git unpack-objects < *.pack
          rm -f *.pack objects/pack/*

      - name: Pin to IPFS
        uses: aquiladev/ipfs-action@master
        id: ipfs
        with:
          path: .
          service: filebase
          pinName: dotfiles
          filebaseBucket: ${{ secrets.FILEBASE_BUCKET }}
          filebaseKey: ${{ secrets.FILEBASE_KEY }}
          filebaseSecret: ${{ secrets.FILEBASE_SECRET }}

      - name: Print IPFS Hash
        run: |
          echo ${{ steps.ipfs.outputs.hash }}
          cd /tmp
          git clone https://${{ secrets.GATEWAY }}/ipfs/${{ steps.ipfs.outputs.hash }}/ dotfiles
          ls -la dotfiles && rm -rf dotfiles
