name: Ipfs Pinning
# mainブランチにpushされたら ipfsにピン留めする
on:
  push:
    branches:
      - main

jobs:
  ipfs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pin to IPFS
        uses: aquiladev/ipfs-action@master
        id: ipfs
        with:
          path: ./README.md
          service: filebase
          pinName: README.md
          filebaseBucket: ${{ secrets.FILEBASE_BUCKET }}
          filebaseKey: ${{ secrets.FILEBASE_KEY }}
          filebaseSecret: ${{ secrets.FILEBASE_SECRET }}

      - name: Print IPFS Hash
        run: |
          echo ${{ steps.ipfs.outputs.hash }}
          echo ${{ steps.ipfs.outputs.cid }}
          echo ${{ steps.ipfs.outputs.ipfs }}
